"use strict";
let activityCursor=null;
const actionNames={register:'注册账号',login:'登录',logout:'退出',upload:'上传作文',preview:'查看反馈',download:'下载文档',retry:'重试批改',succeeded:'批改完成',failed:'批改失败'};
async function loadActivity(more=false){const button=$('#activity-more');button.disabled=true;try{const data=await api('/api/activity'+(more&&activityCursor?'?before='+activityCursor:''));if(!more)$('#activity-list').replaceChildren();for(const event of data.items){const row=document.createElement('div');row.className='activity-row';const when=document.createElement('time');when.textContent=new Date(event.created*1000).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'});when.dateTime=new Date(event.created*1000).toISOString();const action=document.createElement('strong');action.textContent=actionNames[event.action]||event.action;const detail=document.createElement('span');detail.textContent=event.detail;row.append(when,action,detail);$('#activity-list').append(row);}activityCursor=data.next;button.hidden=!activityCursor;$('#activity-empty').hidden=!!$('#activity-list').children.length;}catch(error){$('#activity-empty').hidden=false;$('#activity-empty').textContent=error.message;}finally{button.disabled=false;}}
async function initializeAccount(){try{const user=await api('/api/auth/me');const roleNames={user:'普通用户',vip:'VIP用户',admin:'管理员'};$('#account-name').textContent=user.username;$('#account-name').title=roleNames[user.role]||'普通用户';$('#sidebar-user').textContent=user.username+' · '+(roleNames[user.role]||'普通用户');await Promise.all([loadHistory(),loadActivity()]);if(user.role==='admin'){addAdminNavigation();await loadAdminUsers();}}catch{location.replace('/login');}}
$('#logout').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'});location.replace('/login');}catch(e){notice(e.message,true);}};
$('#activity-refresh').onclick=()=>loadActivity();$('#activity-more').onclick=()=>loadActivity(true);
initializeAccount();

let adminUsers=[];
const roleLabels={user:'普通用户',vip:'VIP 用户',admin:'管理员'};
function renderAdminUsers(){const query=($('#user-search')?.value||'').trim().toLowerCase();const rows=adminUsers.filter(u=>`${u.username} ${u.role}`.toLowerCase().includes(query));$('#users-body').innerHTML=rows.map(u=>`<tr><td>${esc(u.username)}</td><td><span class="badge ${u.role}">${roleLabels[u.role]||u.role}</span></td><td>${u.id}</td></tr>`).join('');$('#users-empty').hidden=rows.length>0;}
async function loadAdminUsers(){try{adminUsers=await api('/api/admin/users');const section=document.createElement('section');section.id='admin-users';section.className='card admin-users';section.innerHTML='<div class="section-head"><div><div class="eyebrow">ADMINISTRATION</div><h2>用户列表</h2></div><label class="search">⌕ <input id="user-search" type="search" placeholder="搜索用户名或权限"></label></div><div class="table-scroll"><table><thead><tr><th>用户名</th><th>权限</th><th>用户 ID</th></tr></thead><tbody id="users-body"></tbody></table></div><p id="users-empty" class="empty" hidden>没有找到匹配的用户。</p>';$('#activity').after(section);$('#user-search').addEventListener('input',renderAdminUsers);renderAdminUsers();}catch(error){if(error.message.includes('Administrator'))return;}}
function addAdminNavigation(){const nav=document.querySelector('.sidebar nav');if(!nav||document.querySelector('#admin-nav'))return;const link=document.createElement('a');link.id='admin-nav';link.href='/admin';link.innerHTML='<span class="nav-icon">⚙</span>运营后台';nav.append(link);}
