const assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm');
const {parseHTML} = require('linkedom');
const {document} = parseHTML(fs.readFileSync('frontend/index.html', 'utf8'));
const context = vm.createContext({document});
for (const name of ['learning.js', 'annotations.js', 'review-language.js']) vm.runInContext(fs.readFileSync('frontend/' + name, 'utf8'), context);
vm.runInContext('globalThis.review = EssayReview; globalThis.language = ReviewLanguage;', context);
const fixture = JSON.parse(fs.readFileSync('tests/fixtures/bilingual-learning.json', 'utf8'));
const preview = {...JSON.parse(fs.readFileSync('tests/fixtures/frontend-contract-preview.json', 'utf8')), ...fixture};
const before = JSON.stringify(preview), render = p => context.review.render(p, text => '<p>' + text + '</p>');
render(preview);
assert.deepEqual(Array.from(document.querySelectorAll('[data-review-tab]'), tab => tab.dataset.reviewTab), ['corrections', 'learning', 'paragraphs']);
assert.match(document.getElementById('tab-learning').textContent, /词汇积累/);
assert.equal(document.querySelectorAll('#panel-learning .learning-card').length, 3);
document.getElementById('tab-learning').click();
assert.equal(document.getElementById('panel-learning').hidden, false);
assert.equal(document.getElementById('panel-corrections').hidden, true);
assert.match(document.getElementById('panel-learning').textContent, /High-score Vocabulary/);
document.querySelector('[data-learning-language="zh"]').click();
assert.match(document.getElementById('panel-learning').textContent, /旅行者可以探索沿海城镇/);
assert.match(document.getElementById('panel-learning').textContent, /原句指主动游览/);
assert.match(document.getElementById('panel-learning').textContent, /Travellers can explore/);
render(preview);
assert.equal(document.getElementById('tab-learning').getAttribute('aria-selected'), 'true');
assert.equal(document.querySelector('[data-learning-language="zh"]').getAttribute('aria-pressed'), 'true');
document.querySelector('[data-learning-language="en"]').click();
assert.doesNotMatch(document.getElementById('panel-learning').textContent, /原句指主动游览/);
assert.equal(JSON.stringify(preview), before);
const unsafe = structuredClone(preview);
unsafe.topic_collocations.items[0].example_sentence = '<script>alert(1)</script>';
render(unsafe);
assert.equal(document.querySelector('#panel-learning script'), null);
render({original:['Historical essay.'], channels:{learning:'unavailable'}});
assert.match(document.getElementById('panel-learning').textContent, /No vocabulary learning content/);
assert.equal(document.querySelectorAll('#panel-learning .learning-card').length, 0);
console.log('Bilingual vocabulary placement, switching, immutable input, legacy and escaping passed.');
